# Generated by Django 5.1.5 on 2025-03-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='media'),
        ),
    ]
