name: Deploy Django App

on:
  push:
    branches:
      - master  # Adjust if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Secrets
        run: |
          echo "VPS_HOST=${{ secrets.VPS_HOST }}"
          echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}"
          

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Connected to VPS"
            /var/www/projects/patent-rag/deploy.sh
